name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .
